#
# torii config for profile [dev]
#
world_address = "0x00b8d2b85a77394f9980a502e1d9f86a4b9219c9065044bd044a59a8f84f1393"
rpc = "https://api.cartridge.gg/x/d20-katana/katana"

[events]
raw = true

[indexing]
# transactions = true
# controllers = true
pending = true
contracts = [
  "erc721:0x0468d3fbf587e6099286aee2e42f4e8e37bf3f95d0dec368f53b2479f51e882f", # explorer_token
  "erc721:0x05b7e1e89e4af223d5a2444e304f9c26500311de3bd2184facc3dd3c39d471d9", # temple_token
]

# [sql]
# historical = [
#   "dojo_starter-Moves",
#   "dojo_starter-Moved",
# ]

