#
# torii config for profile [dev]
#
world_address = "0x0019ad793d43e25c705789ebafaf845727f4ba1ac8185af701472b2b4ecc93d0"
rpc = "https://api.cartridge.gg/x/starknet/sepolia/rpc/v0_9"

[events]
raw = true

[indexing]
# transactions = true
# controllers = true
pending = true
contracts = [
  "erc721:0x0276a9e7e606febaa5240e35198236826049d06d8b58f0589c334fe6525fb8a3", # explorer_token
  "erc721:0x0549d301eef0341da7a293a76639421429a2c38b65ec0887d29e582def92a9a6", # temple_token
]

# [sql]
# historical = [
#   "dojo_starter-Moves",
#   "dojo_starter-Moved",
# ]

