#
# torii config for profile [dev]
#
world_address = "0x0400feed25cca789d09cfdc33debcc94c11703995cb3eb3dae2501fd215d1b3a"
rpc = "http://127.0.0.1:5050"

[events]
raw = true

[indexing]
# transactions = true
# controllers = true
pending = true
contracts = [
  "erc721:0x0468d3fbf587e6099286aee2e42f4e8e37bf3f95d0dec368f53b2479f51e882f", # explorer_token
  "erc721:0x01de2cb4291702e400517c18a6200eb1e16751b3dd498c8e23d8edc1212963e9", # temple_token
]

# [sql]
# historical = [
#   "dojo_starter-Moves",
#   "dojo_starter-Moved",
# ]

